# Generated by Django 4.2 on 2023-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_player_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playresult",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
