# Generated by Django 4.2 on 2023-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_playresult_play_game_alter_playresult_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="points_for_looser",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="points_for_winner",
            field=models.IntegerField(default=0),
        ),
    ]
