# Generated by Django 4.2 on 2023-06-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_game_points_for_looser_game_points_for_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playresult",
            name="points",
            field=models.FloatField(default=0),
        ),
    ]
